# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kasha', '0002_auto_20170206_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='book_source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='en_verse_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='he_verse_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
