# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 01:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kasha', '0003_auto_20170206_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_Questions_Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_chapter_sentence', models.CharField(max_length=100)),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
    ]
