# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kasha', '0007_auto_20170207_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookchapterquestions',
            options={'verbose_name': 'Book Chapter Questions', 'verbose_name_plural': 'Book Chapter Questions'},
        ),
        migrations.RenameField(
            model_name='bookchapterquestions',
            old_name='question_list',
            new_name='verses',
        ),
    ]
