# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kasha', '0008_auto_20170207_2115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookchapterquestions',
            unique_together=set([('book_name', 'chapter')]),
        ),
    ]
